name: disfruta_antofagasta
description: "Museo RapaNui - Isla de Pascua"
publish_to: 'none'

version: 1.0.3+9

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  go_router: ^16.2.1
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  dio: ^5.9.0
  connectivity_plus: ^6.1.5
  google_fonts: ^6.3.1
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  flutter_dotenv: ^6.0.0
  url_launcher: ^6.3.2
  photo_view: ^0.15.0
  pdfx: ^2.9.2
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  flutter_map: ^8.2.1
  latlong2: ^0.9.1
  easy_localization: ^3.0.8
  flutter_secure_storage: ^9.2.4
  get_it: ^8.2.0
  formz: ^0.8.0
  animations: ^2.1.0
  audioplayers: ^6.1.0
  just_audio: ^0.9.42
  mobile_scanner: ^3.5.0

  # ðŸ‘‡ librerÃ­a para renderizar HTML
  flutter_html: ^3.0.0-beta.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/weather/1.png
    - assets/logo.png
    - assets/weather/2.png
    - assets/weather/3.png
    - assets/weather/4.png
    - assets/weather/5.png
    - assets/weather/6.png
    - assets/weather/7.png
    - assets/weather/8.png
    - assets/weather/9.png
    - assets/pdf/antofagasta-mapa-turistico-mobile-small.pdf
    - assets/i18n/es.json
    - assets/i18n/en.json
    - assets/i18n/pt.json
    - assets/i18n/fr.json
    - assets/bg_portada.png
    - assets/logo_museo.png

flutter_launcher_icons:
  android: true
  image_path: "assets/logo_museo.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#ffffff"
  image: assets/logo_museo.png
  android: true
  ios: true
